---
title: "Exploring My Job Hunt"
author: "Charley Cowens"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
  html_document: default
always_allow_html: true
---


```{r packages, include=FALSE}
if(!require(dplyr)) {install.packages("dplyr"); library(dplyr)}
if(!require(magrittr)) {install.packages("magrittr"); library(magrittr)}
if(!require(kableExtra)) {install.packages("kableExtra"); library(kableExtra)}
if(!require(stringr)) {install.packages("stringr"); library(stringr)}
if(!require(tm)) {install.packages("tm"); library(tm)}
if(!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}
if(!require(wordcloud2)) {install.packages("wordcloud2"); library(wordcloud2)}
if(!require(DiagrammeR)) {install.packages("DiagrammeR"); library(DiagrammeR)}
if(!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}
if(!require(webshot)) {install.packages("webshot"); library(webshot)}
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install_phantomjs(force=TRUE)
the_cards <- readRDS("the_cards.rds") %>% 
  filter(ApplyDate>as.Date("2023-12-31") | Status == "Preparing")
```

## Diagrams

### The Flow from Status to Status

```{r diagram1, echo=FALSE, fig.height=4, fig.width=7}
mermaid("
graph LR
    A(Preparing) -->|Sent| B{Applied}
    B -->|Arranged| C{Interview}
    B -->|Bounced| D[Rejected]
    C -->|Notified| D
    C -->|Notified| E{Offer}
    C -->|Waited long enough| F[No Response]
    B --> |Waited long enough| F
    E --> |Yes| G[Acceptance]
    E --> |No| H[Declined]
    style D fill:#f00
    style F fill:#f00
    style H fill:#f00
  ")
```

### Current Count for Each Status Bucket

```{r diagram2, echo=FALSE}
mermaidscript <- paste0(
"graph LR
    A(", "Preparing ", sum(the_cards$Status=='Preparing'), 
    ") --> B{Applied ", sum(the_cards$Status=='Applied'),
    "}
    B --> C{Interview ", sum(the_cards$Status=='Interview'), 
    "}
    B --> D[Rejected ", sum(the_cards$Status=='Rejected'), 
    "]
    C -->|", sum(the_cards$Status=='Rejected' & !is.na(the_cards$InterviewedLast)),  
    "| D
    C --> E{Offer ", sum(the_cards$Status=='Offer'),
    "}
    C -->|", sum(the_cards$Status=='No Response' & !is.na(the_cards$InterviewedLast)), 
    "| F[No Response ", sum(the_cards$Status=='No Response'), 
    "]
    B --> F
    E --> G[Acceptance ", sum(the_cards$Status=='Acceptance'),
    "]
    E --> H[Declined ", sum(the_cards$Status=='Declined'),
    "]
  ")
mermaid(mermaidscript)
```

## Weekly Applications

```{r weekly apps, echo=FALSE}

apps_by_week <- filter(the_cards, !(ApplyWeek == "")) %>% 
  group_by(`Week Starting` = ApplyWeek) %>% 
  summarise(Apps=n()) 

ggplot(apps_by_week, aes(x=`Week Starting`, y=Apps)) + 
  theme_bw() +
  geom_point(size=5, color="green") + 
  geom_segment(aes(x=`Week Starting`, 
                   xend=`Week Starting`, 
                   y=0, 
                   yend=Apps)) + 
  labs(title="Application by Week" ) + 
  theme(axis.text.x = element_text(angle=65, hjust=1, margin=margin(3, 0, 0, 0, "pt")))

ggplot(apps_by_week, aes(x = `Week Starting`, y = Apps)) +
  theme_minimal() +
  geom_col() +
  coord_flip()

```

## Days to Apply from Creating Trello Ticket
```{r rapply, echo=FALSE}

applications <- the_cards %>%  
  filter(!Status=="Preparing") %>% 
  mutate(DaysToApply = as.numeric(ApplyDate-CardCreated))

data.frame(Days = unclass(summary(applications$DaysToApply))) %>% 
  mutate(Days = round(Days,1)) %>% 
  kable() %>% kable_styling("striped", position="left", full_width = FALSE) %>% 
row_spec(0, bold=T)

applications %>% 
  select(Job, Company, DaysToApply) %>%
  arrange(DaysToApply) %>% 
  kable() %>% kable_styling("striped", position="left", full_width = FALSE) %>% 
row_spec(0, bold=T)

```

## Days to Explicit Rejection

```{r rejection, echo=FALSE}

rejects <- the_cards %>%  
  filter(!is.na(Rejected)) %>% 
  mutate(DaysToReject = as.numeric(Rejected-ApplyDate))

data.frame(Days = unclass(summary(rejects$DaysToReject))) %>% 
  mutate(Days = round(Days,1)) %>% 
  kable() %>% kable_styling("striped", position="left", full_width = FALSE) %>% 
row_spec(0, bold=T)

rejects %>% 
  select(Job, Company, DaysToReject) %>%
  arrange(DaysToReject) %>% 
  kable() %>% kable_styling("striped", position="left", full_width = FALSE) %>% 
row_spec(0, bold=T)

```


## Keywords in Job Titles

```{r keywords, echo=FALSE, message=FALSE, warning=FALSE}

# Define your character vector
text_vector <- the_cards$Job %>% str_remove_all("[:punct:]") 
corpus <- Corpus(VectorSource(text_vector)) %>% tm_map(removeWords, stopwords("english"))
dtm <- as.data.frame(as.matrix(DocumentTermMatrix(corpus)))
words <- colSums(dtm)
df <- data.frame(Word=names(dtm), Freq=words) %>% arrange(desc(Freq))

wordcloud2(data=df, size=.5, color='random-light', gridSize = 50)


# Add column names

count_occurrences <- function(strings, vector) {
  counts <- sapply(strings, function(x) sum(str_count(vector, x)))
  data.frame(Contains = strings, Count = counts, row.names = NULL)
}


```

